# Generated by Django 6.0.1 on 2026-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_habits',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
