# Generated by Django 6.0.1 on 2026-01-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_category_habit_task_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habit'),
        ),
    ]
