# Generated by Django 6.0.1 on 2026-01-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_style',
            field=models.CharField(default='Minimal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='focus_preference',
            field=models.CharField(default='One task at a time', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_style',
            field=models.CharField(default='One task at a time', max_length=50),
            preserve_default=False,
        ),
    ]
