# Generated by Django 6.0.1 on 2026-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_userprofile_streak_alter_userprofile_dashboard_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_completed_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
