# Generated by Django 6.0.1 on 2026-02-04 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_userprofile_last_completed_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
