# Generated by Django 6.0.1 on 2026-02-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_tasklog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_style',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('colorful', 'Colorful'), ('goal', 'Goal-Focused')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='focus_preference',
            field=models.CharField(choices=[('calm', 'Calm visuals'), ('bright', 'Bright colors'), ('minimal', 'Minimal distractions'), ('gentle', 'Gentle animations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_style',
            field=models.CharField(choices=[('single', 'One task at a time'), ('pomodoro', 'Short bursts (Pomodoro-style)'), ('long', 'Long focused sessions'), ('free', 'No strict structure')], max_length=50),
        ),
    ]
