# Generated by Django 6.0.1 on 2026-02-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_userprofile_dashboard_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_style',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('colorful', 'Colorful'), ('goal', 'Goal-Focused')], default='minimal', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='focus_preference',
            field=models.CharField(choices=[('calm', 'Calm visuals'), ('bright', 'Bright colors'), ('minimal', 'Minimal distractions'), ('gentle', 'Gentle animations')], default='calm', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_categories',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('wellness', 'Wellness'), ('work', 'Work'), ('creativity', 'Creativty'), ('home', 'Home')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_style',
            field=models.CharField(choices=[('single', 'One task at a time'), ('pomodoro', 'Short bursts (Pomodoro-style)'), ('long', 'Long focused sessions'), ('free', 'No strict structure')], default='one_task', max_length=50),
        ),
    ]
