# Generated by Django 6.0.1 on 2026-02-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_userprofile_dashboard_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_categories',
            field=models.CharField(choices=[('school', 'School'), ('wellness', 'Wellness'), ('work', 'Work'), ('creativity', 'Creativty'), ('home', 'Home')], default='', max_length=50),
        ),
    ]
