# Generated by Django 6.0.1 on 2026-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_userprofile_selected_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_categories',
            field=models.CharField(default='', max_length=200),
        ),
    ]
